[project]
name = "t2asciiart"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.14",
    "numpy>=2.3.1",
    "pillow>=11.2.1",
    "uvicorn>=0.35.0",
]
